### ISSUE TITLE
Replace `request` library with another http library

### ISSUE THREAD

**Issue by gcorne** [HubSpot/cli-lib#25]
The `request` library is deprecated so we need to replace it. This is a significant change to `@hubspot/cms-lib` so I think we'll bump to a new major version.

**Comment by TanyaScales** [comment]
Transferred from hubspot-cli because this is still a deprecated package that is in use

**Comment by TanyaScales** [comment]
After talking with @camden11 - We have a duplicated issue internally to address this -- closing this one out
